server:
  port: 10000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.98.10:3306/app?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: rebound
    password: 1234
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 5MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
#    username, password 각자 이메일과 앱 비밀번호로 입력하시면 됩니다.
    username: hjjung990927
    password: tzxh ixce mkpb perc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
  type-handlers-package: com.example.rebound.config.mybatis.handler
  type-aliases-package: com.example.rebound.domain;com.example.rebound.dto;